# Generated by Django 4.1.3 on 2023-02-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roadname", models.CharField(max_length=100)),
                ("roadcode", models.CharField(max_length=100)),
                (
                    "mc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Road.mc"
                    ),
                ),
            ],
        ),
    ]
